import Footer from "@/components/footer/page";
import Navbar from "@/components/Navbar/page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "landing page",
  description: "Generated by create next app",
};


export default function LandingPageLayout({ children }: LayoutProps<"/">) {
  return (
    
     <div >
        <Navbar/>
   
<div className="mt-30">
     {children}
</div>
       <Footer/>
 
        </div>
         
  )
}